import { useState } from 'react';
import { Table, Button, Tag, Space, Typography, Card, message, Popconfirm } from 'antd';
import { CheckOutlined } from '@ant-design/icons';
import { useGetTimesheetsQuery, useApproveTimesheetMutation } from '../api/clockApi';
import { useAppSelector } from '../store/store';
import type { TimesheetSummary } from '../types';

const { Title } = Typography;

const statusColors: Record<string, string> = { AutoGenerated: 'default', EmployeeSubmitted: 'gold', ManagerApproved: 'green', Locked: 'blue' };

export default function TimesheetPage() {
  const { user } = useAppSelector((s) => s.auth);
  const isManager = user?.role === 'Admin' || user?.role === 'Manager' || user?.role === 'SuperAdmin';
  const [page, setPage] = useState(1);
  const { data, isLoading } = useGetTimesheetsQuery({ page, pageSize: 20 });
  const [approve] = useApproveTimesheetMutation();

  const handleApprove = async (id: string) => {
    try {
      await approve({ id }).unwrap();
      message.success('Timesheet approved');
    } catch {
      message.error('Failed to approve');
    }
  };

  const columns = [
    { title: 'Employee', dataIndex: 'employeeName', key: 'employee' },
    { title: 'Period', key: 'period', render: (_: unknown, r: TimesheetSummary) => `${r.periodStart} — ${r.periodEnd}` },
    { title: 'Regular', dataIndex: 'regularHours', key: 'regular', render: (v: number) => `${v.toFixed(1)}h` },
    { title: 'Overtime', dataIndex: 'overtimeHours', key: 'overtime', render: (v: number) => v > 0 ? <Tag color="orange">{v.toFixed(1)}h</Tag> : '0h' },
    { title: 'Net Hours', dataIndex: 'netPayableHours', key: 'net', render: (v: number) => <strong>{v.toFixed(1)}h</strong> },
    { title: 'Gross Pay', dataIndex: 'totalGrossPay', key: 'pay', render: (v: number) => `CHF ${v.toFixed(2)}` },
    { title: 'Status', dataIndex: 'status', key: 'status', render: (v: string) => <Tag color={statusColors[v]}>{v}</Tag> },
    ...(isManager ? [{
      title: 'Actions', key: 'actions',
      render: (_: unknown, r: TimesheetSummary) => r.status === 'EmployeeSubmitted' ? (
        <Popconfirm title="Approve this timesheet?" onConfirm={() => handleApprove(r.id)}>
          <Button type="text" icon={<CheckOutlined />} style={{ color: 'green' }} size="small">Approve</Button>
        </Popconfirm>
      ) : null,
    }] : []),
  ];

  return (
    <>
      <Title level={3}>Timesheets</Title>
      <Card>
        <Table columns={columns} dataSource={data?.items || []} rowKey="id" loading={isLoading} pagination={{ current: page, pageSize: 20, total: data?.totalCount || 0, onChange: setPage }} />
      </Card>
    </>
  );
}
