// ── Auth ──
export interface LoginRequest { email: string; password: string; }
export interface RegisterRequest { email: string; password: string; firstName: string; lastName: string; organizationName: string; }
export interface LoginResponse { accessToken: string; refreshToken: string; expiresAt: string; user: User; }
export interface User { id: string; email: string; firstName: string; lastName: string; role: string; organizationId: string; organizationName: string; employeeId?: string; }

// ── Employee ──
export interface EmployeeList { id: string; firstName: string; lastName: string; email: string; phone?: string; profilePhotoUrl?: string; status: EmployeeStatus; primaryRoleName?: string; locationName?: string; hireDate: string; }
export interface EmployeeDetail { id: string; firstName: string; lastName: string; email: string; phone?: string; profilePhotoUrl?: string; dateOfBirth?: string; address?: string; city?: string; postalCode?: string; hireDate: string; terminationDate?: string; status: EmployeeStatus; emergencyContactName?: string; emergencyContactPhone?: string; emergencyContactRelation?: string; locationId?: string; locationName?: string; activeContract?: Contract; roles: EmployeeRole[]; }
export interface Contract { id: string; contractType: ContractType; contractedHoursPerWeek: number; hourlyRate: number; salaryMonthly?: number; startDate: string; endDate?: string; probationEndDate?: string; noticePeriodDays: number; isActive: boolean; }
export interface EmployeeRole { roleId: string; roleName: string; roleColor: string; proficiencyLevel: ProficiencyLevel; isPrimary: boolean; }

export type EmployeeStatus = 'Active' | 'OnLeave' | 'Suspended' | 'Terminated';
export type ContractType = 'FullTime' | 'PartTime' | 'Hourly' | 'Internship' | 'Seasonal';
export type ProficiencyLevel = 'Trainee' | 'Junior' | 'Senior' | 'Lead';

// ── Schedule ──
export interface SchedulePeriod { id: string; locationId: string; locationName: string; startDate: string; endDate: string; status: ScheduleStatus; publishedAt?: string; totalAssignments: number; totalEmployees: number; }
export interface SchedulePeriodDetail extends SchedulePeriod { notes?: string; assignments: ShiftAssignment[]; staffingRequirements: StaffingRequirement[]; }
export interface ShiftAssignment { id: string; employeeId: string; employeeName: string; employeePhotoUrl?: string; shiftTemplateId?: string; shiftTemplateName?: string; stationId?: string; stationName?: string; roleId?: string; roleName?: string; roleColor?: string; date: string; startTime: string; endTime: string; breakDurationMinutes: number; status: ShiftAssignmentStatus; netHours: number; notes?: string; }
export interface StaffingRequirement { id: string; roleId: string; roleName: string; dayOfWeek: number; shiftTemplateId?: string; shiftTemplateName?: string; minStaff: number; maxStaff: number; }
export interface ConflictCheck { hasErrors: boolean; conflicts: Conflict[]; }
export interface Conflict { code: string; message: string; severity: 'Error' | 'Warning'; employeeId?: string; }

export type ScheduleStatus = 'Draft' | 'Published' | 'Locked';
export type ShiftAssignmentStatus = 'Scheduled' | 'Confirmed' | 'NoShow' | 'Cancelled';

// ── Time Off ──
export interface TimeOffRequest { id: string; employeeId: string; employeeName: string; leaveTypeId: string; leaveTypeName: string; leaveTypeColor: string; startDate: string; endDate: string; totalDays: number; reason?: string; status: TimeOffStatus; createdAt: string; reviewedBy?: string; reviewedAt?: string; denialReason?: string; }
export interface LeaveBalance { id: string; leaveTypeId: string; leaveTypeName: string; year: number; entitled: number; used: number; carriedOver: number; adjustment: number; remaining: number; }

export type TimeOffStatus = 'Pending' | 'Approved' | 'Denied' | 'Cancelled';

// ── Clock & Timesheet ──
export interface ClockStatus { isClockedIn: boolean; isOnBreak: boolean; lastClockIn?: string; lastBreakStart?: string; currentShiftInfo?: string; workedSoFar?: string; }
export interface ClockEntry { id: string; employeeId: string; entryType: ClockEntryType; timestamp: string; source: string; isManualOverride: boolean; notes?: string; }
export interface TimesheetSummary { id: string; employeeId: string; employeeName: string; periodStart: string; periodEnd: string; regularHours: number; overtimeHours: number; netPayableHours: number; totalGrossPay: number; status: TimesheetStatus; approvedAt?: string; approvedBy?: string; }
export interface PayrollExport { employeeId: string; employeeName: string; employeeEmail?: string; contractType?: string; hourlyRate: number; regularHours: number; overtimeHours: number; regularPay: number; overtimePay: number; totalGrossPay: number; periodStart: string; periodEnd: string; }

export type ClockEntryType = 'ClockIn' | 'ClockOut' | 'BreakStart' | 'BreakEnd';
export type TimesheetStatus = 'AutoGenerated' | 'EmployeeSubmitted' | 'ManagerApproved' | 'Locked';

// ── Settings ──
export interface Role { id: string; name: string; description?: string; defaultHourlyRate: number; color: string; departmentId?: string; departmentName?: string; }
export interface Station { id: string; name: string; description?: string; maxCapacity: number; locationId?: string; locationName?: string; roleIds: string[]; }
export interface Department { id: string; name: string; description?: string; color: string; }
export interface Location { id: string; name: string; address?: string; city?: string; postalCode?: string; phone?: string; latitude?: number; longitude?: number; geofenceRadiusMeters: number; isActive: boolean; }
export interface ShiftTemplate { id: string; name: string; startTime: string; endTime: string; breakDurationMinutes: number; breakIsPaid: boolean; color: string; totalHours: number; netHours: number; isActive: boolean; }
export interface LeaveType { id: string; name: string; isPaid: boolean; requiresDocument: boolean; maxDaysPerYear?: number; accrualRatePerMonth?: number; maxCarryOverDays: number; color: string; }

// ── Notifications ──
export interface Notification { id: string; title: string; message: string; type: string; actionUrl?: string; isRead: boolean; createdAt: string; }
export interface Announcement { id: string; title: string; content: string; isPinned: boolean; postedBy: string; createdAt: string; expiresAt?: string; readCount: number; totalRecipients: number; }

// ── Availability ──
export interface Availability { id: string; dayOfWeek: number; startTime: string; endTime: string; type: string; }
export interface AvailabilityOverride { id: string; date: string; startTime?: string; endTime?: string; type: string; note?: string; }

// ── Dashboard ──
export interface ManagerDashboard { totalEmployees: number; activeToday: number; onLeaveToday: number; pendingTimeOffRequests: number; pendingTimesheets: number; openShiftsCount: number; weeklyLaborHours: number; todayShifts: ShiftAssignment[]; }
export interface EmployeeDashboard { clockStatus: ClockStatus; upcomingShifts: ShiftAssignment[]; leaveBalances: LeaveBalance[]; hoursThisWeek: number; hoursThisPeriod: number; pendingTimeOffRequests: number; }

// ── Common ──
export interface PagedResult<T> { items: T[]; totalCount: number; page: number; pageSize: number; totalPages: number; }
