using StaffPro.Domain.Enums;

namespace StaffPro.Domain.Entities;

public class ClockEntry : TenantEntity
{
    public Guid EmployeeId { get; set; }
    public Employee Employee { get; set; } = null!;

    public ClockEntryType EntryType { get; set; }
    public DateTime Timestamp { get; set; }
    public DateTime? RoundedTimestamp { get; set; }
    public ClockSource Source { get; set; } = ClockSource.WebApp;

    public double? Latitude { get; set; }
    public double? Longitude { get; set; }
    public double? GpsAccuracyMeters { get; set; }
    public string? IpAddress { get; set; }

    public bool IsManualOverride { get; set; }
    public string? OverrideReason { get; set; }
    public string? OverrideBy { get; set; }

    public Guid? ShiftAssignmentId { get; set; }
    public ShiftAssignment? ShiftAssignment { get; set; }
}

public class Timesheet : TenantEntity
{
    public Guid EmployeeId { get; set; }
    public Employee Employee { get; set; } = null!;

    public DateOnly PeriodStart { get; set; }
    public DateOnly PeriodEnd { get; set; }

    public decimal RegularHours { get; set; }
    public decimal OvertimeHours { get; set; }
    public decimal NightHours { get; set; }
    public decimal WeekendHours { get; set; }
    public decimal BreakHours { get; set; }
    public decimal NetPayableHours { get; set; }

    public decimal RegularPayCents { get; set; }
    public decimal OvertimePayCents { get; set; }
    public decimal TotalGrossPayCents { get; set; }

    public TimesheetStatus Status { get; set; } = TimesheetStatus.AutoGenerated;
    public DateTime? SubmittedAt { get; set; }
    public DateTime? ApprovedAt { get; set; }
    public string? ApprovedBy { get; set; }
    public string? Notes { get; set; }

    public ICollection<TimesheetEntry> Entries { get; set; } = [];
}

public class TimesheetEntry : TenantEntity
{
    public Guid TimesheetId { get; set; }
    public Timesheet Timesheet { get; set; } = null!;

    public DateOnly Date { get; set; }
    public DateTime? ClockIn { get; set; }
    public DateTime? ClockOut { get; set; }
    public decimal BreakMinutes { get; set; }
    public decimal RegularHours { get; set; }
    public decimal OvertimeHours { get; set; }
    public bool IsNoShow { get; set; }
    public string? Notes { get; set; }

    public Guid? ShiftAssignmentId { get; set; }
    public ShiftAssignment? ShiftAssignment { get; set; }
}
