namespace StaffPro.Domain.Enums;

public enum EmployeeStatus
{
    Active = 0,
    OnLeave = 1,
    Suspended = 2,
    Terminated = 3
}

public enum ContractType
{
    FullTime = 0,
    PartTime = 1,
    Hourly = 2,
    Internship = 3,
    Seasonal = 4
}

public enum ProficiencyLevel
{
    Trainee = 0,
    Junior = 1,
    Senior = 2,
    Lead = 3
}

public enum AvailabilityType
{
    Available = 0,
    Preferred = 1,
    Unavailable = 2
}

public enum SchedulePeriodStatus
{
    Draft = 0,
    Published = 1,
    Locked = 2
}

public enum ShiftAssignmentStatus
{
    Scheduled = 0,
    Confirmed = 1,
    NoShow = 2,
    Cancelled = 3
}

public enum TimeOffRequestStatus
{
    Pending = 0,
    Approved = 1,
    Denied = 2,
    Cancelled = 3
}

public enum ClockEntryType
{
    ClockIn = 0,
    ClockOut = 1,
    BreakStart = 2,
    BreakEnd = 3
}

public enum ClockSource
{
    WebApp = 0,
    KioskPin = 1,
    KioskQr = 2,
    ManagerOverride = 3
}

public enum TimesheetStatus
{
    AutoGenerated = 0,
    EmployeeSubmitted = 1,
    ManagerApproved = 2,
    Locked = 3
}

public enum ConflictSeverity
{
    Error = 0,
    Warning = 1
}

public enum NotificationType
{
    SchedulePublished = 0,
    ShiftAssigned = 1,
    ShiftChanged = 2,
    TimeOffRequestStatus = 3,
    TimesheetReminder = 4,
    CertificationExpiring = 5,
    AnnouncementPosted = 6,
    OpenShiftAvailable = 7,
    ShiftSwapRequest = 8
}

public enum AnnouncementTargetType
{
    All = 0,
    Department = 1,
    Location = 2,
    Role = 3
}

public enum Permission
{
    ViewSchedule = 0,
    CreateSchedule = 1,
    PublishSchedule = 2,
    ApproveTimeOff = 3,
    ViewPayroll = 4,
    EditEmployees = 5,
    ManageRoles = 6,
    ViewAllDepartments = 7,
    ApproveTimesheets = 8,
    OverrideConflicts = 9,
    ManageSettings = 10,
    ViewReports = 11,
    ManageAnnouncements = 12,
    ClockOverride = 13
}

public enum AppRole
{
    SuperAdmin = 0,
    Admin = 1,
    Manager = 2,
    Employee = 3
}
